# Generated by Django 5.2.2 on 2025-06-07 18:22

from django.db import migrations


def populate_role(apps, schemaeditor):
    entries = {
        "developer": "Responsible for writing and maintaining code.",
        "product owner": "Defines product vision and prioritizes features.",
        "scrum master": "Facilitates scrum processes and removes impediments.",
    }
    Role = apps.get_model('accounts', 'Role')
    for key, value in entries.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_role)
    ]