# Generated by Django 5.2.2 on 2025-06-07 18:22

from django.db import migrations

def populate_team(apps, schemaeditor):
    entries = {
        "alpha": "Team Alpha, focused on core product development.",
        "bravo": "Team Beta, responsible for testing and quality assurance.",
        "charlie": "Team Gamma, handling customer support and feedback.",
    }
    Team = apps.get_model('accounts', 'Team')
    for key, value in entries.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250607_1822'),
    ]

    operations = [
        migrations.RunPython(populate_team)
    ]
